### ISSUE TITLE
Missing instance types (e.g. n2)

### ISSUE THREAD

**Issue by doit-mattporter** [doitintl/gcpinstances.info#16]
The list of instances isn't complete, even for machine types that have been around for some time. For example, n2-highmem-96 is missing while all other n2-highmem machines are present.

**Comment by Burekasim** [comment]
Hi @doit-mattporter 
Thank you for bringing this to our attention

I checked and the following instances are missing:
e2-standard-32
n2-highcpu-965
n2-highmem-1285
n2-highmem-965
n2-standard-1285
n2-standard-965

I will make sure to add the data soon.

**Comment by Burekasim** [comment]
Hi @doit-mattporter, 

The following instance types were missing:
e2-standard-32
e2-highcpu-32
n2-standard-96
n2-standard-128
n2-highcpu-96
n2-highmem-96
n2-highmem-128

In the last commit, I've added the instances to the database.
