### ISSUE TITLE
n2-standard-8 shows "Linux On Demand cost" as "Unavailable"

### ISSUE THREAD

**Issue by quinncomendant** [doitintl/gcpinstances.info#24]
The `n2-standard-*` machine types show `Unavailable` in the Linux On Demand and Linux Sustained usage discount cost columns. The pricing is clearly available from Google, so why does it say “Unavailable”?
![Screen Shot 2022-01-23 at 14 50 55](https://user-images.githubusercontent.com/6884276/150697599-93d3cc27-3dce-4254-b95b-535a1aed2484.png)
![Screen Shot 2022-01-23 at 14 51 17 1](https://user-images.githubusercontent.com/6884276/150697601-5e3a8b30-03bf-46d0-8200-f7f6c0dcd402.png)

**Comment by Burekasim** [comment]
Hi @quinncomendant 

It's definitely a bug, I will fix it in a few hours.

**Comment by Burekasim** [comment]
Hi @quinncomendant, 

Fixed. the prices are now updated.

**Comment by quinncomendant** [comment]
Thanks @Burekasim! Looks good.
