### ISSUE TITLE
Update available CPU types

### ISSUE THREAD

**Issue by quinncomendant** [doitintl/gcpinstances.info#25]
Hi @Burekasim,

I just noticed the CPU Type info is out of date. For example, gcpinstances.info shows most n2-* machine types as having only Cascade Lake CPUs available, while in fact it supports both Cascade Lake and the newer Ice Lake. 

I'm not sure if you're able to pull this data from an API, but in case it's manually entered I've gone ahead and taken screenshots of the all the CPU types available for each machine type in case it's helpful for you.

Note: in the first few screenshots you'll notice a CPU Type that is greyed-out. That's not actually a CPU type available on that machine type, it's just displayed because it was the CPU type that was selected before I changed the Machine type. Only the non-grey CPU types are available for the machine type.

<img width="547" alt="Screen Shot 2022-01-26 at 13 26 42" src="https://user-images.githubusercontent.com/6884276/151288438-a31d9e64-177f-4642-902b-b96cf0267636.png">
<img width="528" alt="Screen Shot 2022-01-26 at 13 26 28" src="https://user-images.githubusercontent.com/6884276/151288464-faee089a-45c1-4a04-a605-e1b5c2686e20.png">
<img width="547" alt="Screen Shot 2022-01-26 at 13 26 54" src="https://user-images.githubusercontent.com/6884276/151288430-7e4e57cf-8b0e-4a84-b4a2-4a552a79dbef.png">
<img width="525" alt="Screen Shot 2022-01-26 at 13 27 08" src="https://user-images.githubusercontent.com/6884276/151288397-ff6f09c6-805e-429d-a158-07d644703303.png">
<img width="533" alt="Screen Shot 2022-01-26 at 13 27 35" src="https://user-images.githubusercontent.com/6884276/151288353-33ab5af0-ebfb-4f4a-9980-e851a31bf70c.png">
<img width="540" alt="Screen Shot 2022-01-26 at 13 27 45" src="https://user-images.githubusercontent.com/6884276/151288329-1791540e-6935-46de-b3d3-e68ab335f2cd.png">
<img width="530" alt="Screen Shot 2022-01-26 at 13 27 56" src="https://user-images.githubusercontent.com/6884276/151288286-e77235df-aa91-424c-b5db-578efe83fcbd.png">
<img width="524" alt="Screen Shot 2022-01-26 at 13 28 08" src="https://user-images.githubusercontent.com/6884276/151288248-a285550d-1cc5-460b-bbc0-977270942cf3.png">

**Comment by Burekasim** [comment]
Hi @quinncomendant, 

Thanks for bringing this to my attention, 
I updated the data according to [this page](https://cloud.google.com/compute/docs/machine-types), that was the source for the original data. 

If there is any discrepancy between the console and the documentation page, please let me know and I will ask GCP support for clarification. 

Best regards,
Burekasim ;)

**Comment by quinncomendant** [comment]
Hi @ Burekasim,

Looks good. The values you entered match what appears in the GUI when creating a VM. 👍
