### ISSUE TITLE
memory is in GB not Gib

### ISSUE THREAD

**Issue by VincentPoncet** [doitintl/gcpinstances.info#27]
https://github.com/doitintl/gcpinstances.info/blob/59f814b523cc23682c3d4889cd661d68bf8385b7/default.js#L224
The code seems to use "GiB", but the app print "Gib"
https://gcpinstances.doit-intl.com/
Gib = 1024^3 of bits
GiB = 1024^3 of bytes

**Comment by Burekasim** [comment]
Hi @VincentPoncet 

Thanks for pointing this out, I updated the file in the app storage and it's now Ok.
