### ISSUE TITLE
e2-medium wrong vCPU count

### ISSUE THREAD

**Issue by dry4ng** [doitintl/gcpinstances.info#31]
The e2-medium vCPU count shown as 1. I have it deployed and I see 2 vCPUs. Official docs also show it as 2 vCPU instance.
<img width="969" alt="Screen Shot 2022-09-12 at 22 51 45" src="https://user-images.githubusercontent.com/34044009/189803776-25bb8402-c550-47c8-8a48-7eee8b7b383b.png">

**Comment by Burekasim** [comment]
Hi @dry4ng 

Thanks for bringing this to my attention, I've updated the instances specs and now it shows the correct numbers.
