### ISSUE TITLE
Currency conversion not working

### ISSUE THREAD

**Issue by atward** [doitintl/gcpinstances.info#33]
All non-USD currencies are showing `0. monthly` in the table, eg:
![image](https://user-images.githubusercontent.com/5027130/195489692-bcf7845e-b4a4-4cbe-9004-d2fabc77d195.png)
![image](https://user-images.githubusercontent.com/5027130/195489714-14cb7492-76d3-47fb-8b15-2cf95b47903b.png)

**Comment by Burekasim** [comment]
Hi Adam, 

Thanks for opening this issue, there was a problem with the currency API key, I fixed it.
