### ISSUE TITLE
Contents of "Region" and "Columns" dropdowns dont scroll

### ISSUE THREAD

**Issue by gdubicki** [doitintl/gcpinstances.info#39]
Hi,

I think that since the style has been updated in https://github.com/doitintl/gcpinstances.info/pull/38 (and I agree that the site is prettier now!) the dropdowns "Region" and "Columns" don't scroll.

<img width="350" alt="Screenshot 2023-04-28 at 09 46 12" src="https://user-images.githubusercontent.com/566632/235101169-5d244d6a-6887-4dab-a152-ad811cc350b8.png">

This is a problem especially for the Regions as the list is long enough to not fit on my big monitor and I have to resort to scrolling with keyboard arrows.

**Comment by Burekasim** [comment]
@noavrd can you please take a look?

**Comment by noavrd** [comment]
@Burekasim will do

**Comment by gdubicki** [comment]
Guys, this is still an issue. And it's really annoying as I need to scroll my keyboard to see the US-based regions, which I am interested in.
