### ISSUE TITLE
Sort doesn't work anymore when Currency is set to Eur

### ISSUE THREAD

**Issue by tpoindessous** [doitintl/gcpinstances.info#40]
Hello ! 

Thanks for your work ! 

When I set the Currency to Eur, ordering of items changes, and I can't sort by machine type , or SUD. But sorting by cpu and memory works as normal.

<img width="801" alt="Capture d’écran 2023-05-30 à 19 13 18" src="https://github.com/doitintl/gcpinstances.info/assets/3054608/f506216c-e093-486f-94c9-62e8b2016b2c">

I'm on Chrome on macOS.

Thanks !

**Comment by Burekasim** [comment]
Hi @tpoindessous 

I'm sorry for the delay, this was fixed today.

**Comment by tpoindessous** [comment]
Thanks for your work !
