### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by gdubicki** [doitintl/gcpinstances.info#48]
<img width="1173" alt="Screenshot 2023-10-17 at 15 09 53" src="https://github.com/doitintl/gcpinstances.info/assets/566632/65141c7c-c2ac-435b-b1dd-7915a85272f4">

**Comment by Burekasim** [comment]
CAA issue, working on a fix.

**Comment by Burekasim** [comment]
Fixed. thanks for reporting ;)
