### ISSUE TITLE
Add n4 instance types

### ISSUE THREAD

**Issue by mwarkentin** [doitintl/gcpinstances.info#55]
Intro blog post: https://cloud.google.com/blog/products/compute/compute-and-infrastructure-enhancements-at-next24

Pricing details: https://cloud.google.com/compute/vm-instance-pricing

**Comment by Burekasim** [comment]
Hi @mwarkentin 
I added the n4 instances manually from the website (we usually scrape the data from the calculator, which will update in a couple of weeks). 

can you double check the numbers from your end?

**Comment by mwarkentin** [comment]
@Burekasim thanks! I tried to spot check things against their docs, and it looks right to me.

Just noticed that the cpu/mem ratio for n4-highcpu changed from the n2-highcpu thanks to this - appreciate it!
