### ISSUE TITLE
C2D does not get sustained use discounts

### ISSUE THREAD

**Issue by evanj** [doitintl/gcpinstances.info#56]
The following line of code computes C2D as having a 20% sustained use discount. However, C2D does not has sustained use discounts. See:

* https://cloud.google.com/compute/docs/general-purpose-machines#t2d_machines
* "Sustained use discounts apply to only N1, N2, N2D, C2, M1, and M2 machine types." https://cloud.google.com/compute/docs/sustained-use-discounts

https://github.com/doitintl/gcpinstances.info/blob/4c2c07a01036842de70d4e7a703101399944462b/scraper.py#L32

I believe this *also* means this line is wrong for T2A:

https://github.com/doitintl/gcpinstances.info/blob/4c2c07a01036842de70d4e7a703101399944462b/scraper.py#L38

**Comment by Burekasim** [comment]
Hi @evanj 

Thank you very much for raising this issue. I've updated the scraper.py settings and the pricing. 

:)

**Comment by evanj** [comment]
LGTM thanks!
