### ISSUE TITLE
Feature: retrieve performance information

### ISSUE THREAD

**Issue by jawnsy** [doitintl/gcpinstances.info#9]
Google provides benchmark data in the form of Coremark scores, so to evaluate price/performance, it would be nice if this site also scraped those scores in a way that allowed things to be correlated, either by adding them as columns to the existing sheet or using a key that we could join against.

Linux benchmarks: https://cloud.google.com/compute/docs/benchmarks-linux
Windows benchmarks: https://cloud.google.com/compute/docs/benchmarks-windows

**Comment by Burekasim** [comment]
@jawnsy thanks for writing this issue,
I pulled all the information for the Linux benchmark, it will be available in a few days.

**Comment by jawnsy** [comment]
I filed a ticket through the DoiT CMP and Wayman Smith replied:

>This functionality has been implemented and can be utilized by selecting the "Linux Coremark benchmark" item in the "Column" menu. Please see the screenshot below for a visual representation.
>
> ![image](https://user-images.githubusercontent.com/52710/141188221-8c0072e0-c150-4799-a680-fc6a96208663.png)

Thanks for this! So this request is resolved and I'm closing the issue.
